# These are supported funding model platforms

patreon: 21456686
open_collective: smilofoundation
ko_fi: smilofoundation
community_bridge: bed87383-0670-43a8-8ea9-9d1f13d4f676
liberapay: smilofoundation
issuehunt: thomasmodeneis # Replace with a single IssueHunt username
