version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/go-smilo
    steps:
      - checkout
      - save_cache: # Store cache in the /go/pkg directory
          key: docker-ethash-cache
          paths:
            - "~/.docker"
            - "~/.ethash"
      - run:
          name: Run hive tests
          command: |
            go get -u github.com/Smilo-platform/hive
            (cd /go/src/github.com/Smilo-platform/hive && mkdir -p workspace/ethash/ ~/.ethash)
            (cd /go/src/github.com/Smilo-platform/hive && cp -r ~/.ethash/. workspace/ethash/)
            (cd /go/src/github.com/Smilo-platform/hive && hive --docker-noshell --client=NONE --test=. --sim=. --loglevel=6)

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
